# Generated by Django 6.0.8 on 2026-09-05 18:20

import django.db.models.deletion
import django_mongodb_backend.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('school_config', '0003_grade_schoolclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.academicyear')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fee_structures', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='school_config.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='school_config.school')),
            ],
            options={
                'db_table': 'fee_structures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structure_items', to='school_config.feecategory')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.feestructure')),
            ],
            options={
                'db_table': 'fee_structure_items',
                'constraints': [models.UniqueConstraint(fields=('fee_structure', 'fee_category'), name='unique_fee_category_per_structure')],
            },
        ),
    ]
