# Generated by Django 6.0.8 on 2026-08-30 09:48

import django.db.models.deletion
import django_mongodb_backend.fields
import payables.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0005_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFinancialProfile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('base_salary_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Financial Profile',
                'verbose_name_plural': 'Employee Financial Profiles',
                'db_table': 'employee_financial_profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeFinancialTransaction',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(default=payables.models.generate_employee_financial_transaction_number, editable=False, max_length=40, unique=True)),
                ('transaction_type', models.CharField(choices=[('advance', 'Financial Advance'), ('reimbursement', 'Reimbursement'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('payment', 'Payment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('voided', 'Voided')], default='posted', editable=False, max_length=20)),
                ('void_reason', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_employee_financial_transactions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='payables.employeefinancialprofile')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_employee_financial_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Financial Transaction',
                'verbose_name_plural': 'Employee Financial Transactions',
                'db_table': 'employee_financial_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
