# Generated by Django 6.0.8 on 2026-08-31 11:28

import django.db.models.deletion
import django_mongodb_backend.fields
import payables.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0006_employeefinancialprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(default=payables.models.generate_approval_request_number, editable=False, max_length=40, unique=True)),
                ('operation_type', models.CharField(choices=[('discount', 'Discount'), ('scholarship', 'Scholarship'), ('refund', 'Refund'), ('financial_assistance', 'Financial Assistance'), ('invoice_cancellation', 'Invoice Cancellation'), ('payment_voiding', 'Payment Voiding'), ('high_value_expense', 'High-Value Expense'), ('other', 'Other Sensitive Adjustment')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=80)),
                ('related_entity_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='requested', editable=False, max_length=25)),
                ('request_reason', models.TextField(blank=True)),
                ('decision_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_approvals', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_approvals', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
