# Generated by Django 6.0.8 on 2026-09-01 08:53

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
import payables.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0007_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_number', models.CharField(default=payables.models.generate_discount_number, editable=False, max_length=40, unique=True)),
                ('discount_type', models.CharField(choices=[('sibling', 'Sibling Discount'), ('early_payment', 'Early Payment Discount'), ('employee_child', 'Employee Child Discount'), ('promotional', 'Promotional Discount'), ('special', 'Special Discount'), ('other', 'Other')], max_length=30)),
                ('value_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('student_reference', models.CharField(max_length=120)),
                ('invoice_reference', models.CharField(max_length=120)),
                ('requires_approval', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=30)),
                ('discount_date', models.DateField(default=django.utils.timezone.localdate)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_records', to='payables.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_discounts', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_discounts', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_discounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
                'ordering': ['-discount_date', '-created_at'],
            },
        ),
    ]
