# Generated by Django 6.0.8 on 2026-09-02 11:08

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
import payables.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0009_scholarship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAssistanceRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_number', models.CharField(default=payables.models.generate_financial_assistance_number, editable=False, max_length=40, unique=True)),
                ('student_reference', models.CharField(max_length=120)),
                ('academic_year_reference', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('supporting_document', models.FileField(blank=True, upload_to='financial_assistance/%Y/%m/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', editable=False, max_length=30)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('review_started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_assistance_records', to='payables.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_financial_assistance', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_financial_assistance', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_financial_assistance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Assistance Request',
                'verbose_name_plural': 'Financial Assistance Requests',
                'db_table': 'financial_assistance_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
