# Generated by Django 6.0.8 on 2026-09-05 09:18

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
import payables.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0011_refund'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_number', models.CharField(default=payables.models.generate_payment_reminder_number, editable=False, max_length=40, unique=True)),
                ('invoice_reference', models.CharField(max_length=120)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('reminder_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_method', models.CharField(choices=[('in_system', 'In-System Notification'), ('email', 'Email')], max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('failure_reason', models.TextField(blank=True, editable=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_payment_reminders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_reminders', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminders', to='students.guardian')),
                ('sent_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_payment_reminders', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminders', to='students.student')),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'db_table': 'payment_reminders',
                'ordering': ['-created_at'],
            },
        ),
    ]
