# Generated by Django 6.0.8 on 2026-08-31 08:32

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(blank=True, null=True, upload_to='school/logos/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('default_currency', models.CharField(choices=[('USD', 'USD — US Dollar'), ('LBP', 'LBP — Lebanese Pound')], default='USD', max_length=3)),
                ('time_zone', models.CharField(default='Asia/Beirut', max_length=60)),
                ('invoice_prefix', models.CharField(default='INV', max_length=15)),
                ('receipt_prefix', models.CharField(default='REC', max_length=15)),
                ('expense_prefix', models.CharField(default='EXP', max_length=15)),
                ('current_academic_year', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'School',
                'db_table': 'school',
            },
        ),
    ]
